import { createHash, randomBytes, randomUUID } from "node:crypto";
import bcrypt from "bcryptjs";
import type { AstroCookies } from "astro";
import { db, row } from "./db";
export type SessionUser={id:number;username:string;role:"usuario"|"administrador"};
const cookieName="fit360_session";const sessionSeconds=60*60*24*7;const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function setSession(cookies:AstroCookies,user:SessionUser,request?:Request){const token=randomBytes(32).toString("base64url");const expiration=new Date(Date.now()+sessionSeconds*1000).toISOString();await db.execute({sql:"INSERT INTO auth_session(id_session,id_usuario,token_hash,user_agent,ip_address,fecha_expiracion) VALUES (?,?,?,?,?,?)",args:[randomUUID(),user.id,hashToken(token),request?.headers.get("user-agent")??null,request?.headers.get("x-forwarded-for")??null,expiration]});cookies.set(cookieName,token,{httpOnly:true,sameSite:"lax",secure:import.meta.env.PROD,path:"/",maxAge:sessionSeconds})}
export async function clearSession(cookies:AstroCookies){const token=cookies.get(cookieName)?.value;if(token)await db.execute({sql:"UPDATE auth_session SET fecha_revocacion=CURRENT_TIMESTAMP WHERE token_hash=?",args:[hashToken(token)]});cookies.delete(cookieName,{path:"/"})}
export async function readSession(cookies:AstroCookies):Promise<SessionUser|null>{const token=cookies.get(cookieName)?.value;if(!token)return null;const session=await row<any>("SELECT u.id_usuario,u.nombre_usuario,u.rol FROM auth_session s JOIN usuario u ON u.id_usuario=s.id_usuario WHERE s.token_hash=? AND s.fecha_revocacion IS NULL AND datetime(s.fecha_expiracion)>datetime('now') AND u.esta_activo=1",[hashToken(token)]);if(!session){cookies.delete(cookieName,{path:"/"});return null}await db.execute({sql:"UPDATE auth_session SET ultimo_uso=CURRENT_TIMESTAMP WHERE token_hash=?",args:[hashToken(token)]});return{id:Number(session.id_usuario),username:session.nombre_usuario,role:session.rol}}
export async function verifyPassword(userId:number,password:string,stored:string){if(stored.startsWith("$2"))return bcrypt.compare(password,stored);if(password!==stored)return false;await db.execute({sql:'UPDATE usuario SET hash_contraseña=? WHERE id_usuario=?',args:[await bcrypt.hash(password,12),userId]});return true}
export async function hasPermission(userId:number,permission:string){return Boolean(await row("SELECT 1 FROM usuario_rol ur JOIN rol_permiso rp ON rp.id_rol=ur.id_rol JOIN permiso p ON p.id_permiso=rp.id_permiso WHERE ur.id_usuario=? AND p.codigo=? LIMIT 1",[userId,permission]))}
